const NOTIFICATION_ADD = 'NOTIFICATION_ADD';
const NOTIFICATION_REMOVE = 'NOTIFICATION_REMOVE';
const NOTIFICATIONS_SET = 'NOTIFICATION_SET';
const NOTIFICATION_CLEAR = 'NOTIFICATION_CLEAR';

export default {
    NOTIFICATION_ADD,
    NOTIFICATION_REMOVE,
    NOTIFICATIONS_SET,
    NOTIFICATION_CLEAR
};