const CART_ADD_OR_UPDATE_ITEM = 'CART_ADD_OR_UPDATE_ITEM';
const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
const CART_CLEAR = 'CART_CLEAR';

export default {
    CART_ADD_OR_UPDATE_ITEM,
    CART_REMOVE_ITEM,
    CART_CLEAR
};